controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
#añadido del video
index:
    path: /
    controller: App\Controller\QuestionController::homepage

